### ISSUE TITLE
Over time, Windscribe flags this as unusual account activity: potential solution? 

### ISSUE THREAD

**Issue by connwork** [dhruvinsh/ws-ephemeral#9]
Every time this logs in, it creates a new session. This can lead to many new sessions over the course of a short time. 

Windscribe eventually reports this as "suspicious activity". Although I haven't gotten a ban, I get many emails about this warning me. 

Is there any way to cache login info or preserve login cookies in a static volume so that it does not have to continuously log in every time the container starts?

**Comment by dhruvinsh** [comment]
That is strange,

By default it run every 6th day at 2:00 am only one time. 

I am wondering that is this container running behind a some proxy network or vpn network?

**Comment by connwork** [comment]
Each time this logs in, it creates a new session though. So over the course of say three months, that would be considered 12 new sessions.

My server restarts maybe twice per week for maintenance, etc,jumping this to 24 sessions. I've gotten many emails.

A simple solution would be just to persist required data to remember a login.

**Comment by dhruvinsh** [comment]
I will take a look, what can be done.

Meanwhile you can take advantage of the ONSHOT env in conjunction with cron job.

**Comment by dhruvinsh** [comment]
Give v3.0.0 a try. Do check the readme with updated instruction.
